[phases.setup]
nixPkgs = ['python311', 'python311Packages.pip', 'postgresql']

[phases.install]
cmds = ['python3 -m pip install -r requirements.txt']

[phases.build]
cmds = ['python3 manage.py collectstatic --noinput']

[start]
cmd = 'python3 manage.py migrate && python3 manage.py init_admin && gunicorn ekitilaw_project.wsgi --bind 0.0.0.0:$PORT'
